#!/usr/bin/env bash

# Check if the current branch is main or in a detached state
branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD)

if [[ "$branch" == "main" ]]; then
  echo "You are on the main branch. Committing directly to main is not allowed."
  exit 1
fi

pnpm lint-staged
