name: Publish to NPM

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10.6.5
                  run_install: true
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: Build Package
              run: pnpm build
            - name: Publish Package
              run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            